import Link from 'next/link';
import PageHero from '../components/PageHero';
import MethodStrip from '../components/MethodStrip';
import InterfacePanel from '../components/InterfacePanel';

const capabilities=[
  ['Intelligence','Corporate, operational, reputational and strategic intelligence built around a defined question.','/intelligence'],
  ['Investigations','Structured support for complex enquiries, timelines, contradictions, hypotheses and evidence reconstruction.','/investigations'],
  ['Digital Evidence','Digital material preserved and assessed with provenance and limitations visible.','/digital-evidence-osint'],
  ['OSINT','Lawful public-source research using tested tools and sources, with verification before findings are relied upon.','/digital-evidence-osint'],
  ['Monitoring','Controlled monitoring of organisations, assets, domains, risks, public sources and material changes.','/monitoring-risk'],
  ['Technology','IRIS Intelligence, HIVE evidence, VITA challenge, VERA verification and bespoke analytical tooling.','/iris-intelligence']
];

export default function Home(){return <>
  <PageHero title={<>Intelligence you can trace.<br/>Investigations you can defend.</>} secondary={{label:'Explore IRIS Investigations',href:'/iris-intelligence'}}>Human-led intelligence, digital evidence, investigation technology and governed AI — built to turn fragmented information into defensible decisions.</PageHero>
  <section className="trustbar"><span>Independent.</span><span>Precise.</span><span>Human.</span><b>ORVIA Oversight Ltd</b></section>
  <section className="section split"><div><div className="eyebrow">EVIDENCE DISCIPLINE</div><h2>A source is not a fact.</h2><p>Search results, records, images, accounts, alerts and datasets can all be useful. None should become a conclusion simply because they exist.</p><p className="lead-small">Every material finding should show what supports it, what contradicts it, what remains unknown and who verified it.</p></div><div><MethodStrip items={['Collect','Preserve','Corroborate','Challenge','Verify','Human Review']}/></div></section>
  <section className="section tone"><div className="section-head"><div><div className="eyebrow">CAPABILITY</div><h2>One discipline. Six routes.</h2></div><p>Start with the question, not the tool. ORVIA routes intelligence work through bounded capabilities with evidence, challenge and verification visible throughout.</p></div><div className="card-grid">{capabilities.map(([t,c,h],i)=><Link href={h} className="cap-card" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p><strong>Explore {t} →</strong></Link>)}</div></section>
  <section className="section"><div className="section-head"><div><div className="eyebrow">IRIS INTELLIGENCE</div><h2>One investigation workspace. Every layer visible.</h2></div><p>IRIS coordinates the work. HIVE preserves the evidence trail. VITA challenges the developing view. VERA verifies material assertions. People retain authority over consequential conclusions.</p></div><InterfacePanel/></section>
  <section className="section dark"><div className="section-head inverse"><div><div className="eyebrow">REPORTING</div><h2>Built to be read. Built to be challenged.</h2></div><p>ORVIA reports separate evidence, analysis, uncertainty and required action instead of burying decision-makers in data dumps.</p></div><div className="report-list">{['Executive Intelligence Brief','Corporate Due Diligence Report','Investigation Report','Threat & Exposure Assessment','Evidence & Chronology Pack','Entity / Network Map','Monitoring Report','Board Intelligence Brief','Digital Evidence Report','Bespoke Intelligence Model'].map(x=><div key={x}>{x}</div>)}</div><Link href="/reports" className="text-link light">Explore Reports →</Link></section>
  <section className="section split"><div><div className="eyebrow">TECHNOLOGY GOVERNANCE</div><h2>The tool is never the truth.</h2><p>ORVIA continuously researches, tests and reviews open-source, free, freemium, commercial and API-enabled intelligence tools.</p><p>A tool enters operational use only when its value, security, provenance and limitations are understood.</p></div><MethodStrip items={['Discover','Sandbox','Test','Score','Approve','Integrate','Review']}/></section>
  <section className="section human"><div className="human-panel"><div className="eyebrow">HUMAN AUTHORITY</div><h2>Powerful technology. Human authority.</h2><p>ORVIA does not automate guilt, culpability, safeguarding findings or other high-consequence decisions.</p><div className="mini-grid"><span>Search</span><span>Organise</span><span>Compare</span><span>Challenge</span><span>Identify gaps</span><span>Assist verification</span></div><strong className="boundary-line">No hidden scoring. No black-box finding. No “AI says so.”</strong></div></section>
  <section className="section boundary"><div><div className="eyebrow">BOUNDARIES</div><h2>Capability with boundaries.</h2><p>ORVIA is not police, an intelligence service, a regulator, a court or a statutory investigative body. We do not claim hacking, covert interception, unrestricted CCTV access, bypassing access controls or guaranteed detection.</p></div><Link className="btn btn-primary" href="/about-governance">Read our governance</Link></section>
  <section className="cta-band"><div><div className="eyebrow">START WITH THE QUESTION</div><h2>What do you need to understand?</h2><p>Tell us the decision you need to support. We will begin with scope, authority and the evidence already available.</p></div><Link href="/contact" className="btn btn-light">Start an Intelligence Review</Link></section>
</>}
